"""Premium Bond Monte Carlo analysis.

@author: Jason Shiers

Reads simulation files generated by sim tool and prints and plots
median and quartile data for various holding sizes
"""

import matplotlib.pyplot as plt
import polars as pl
import seaborn as sns


def group_df(df: pl.DataFrame, holding_size: int = 100_000,
             holding_span: int = 1) -> pl.DataFrame:
    """Group df into simulation groups.

    Groups by holding_span in months and filters bonds to the holding_size

    Returns:
        A dataframe of total winnings for each sim_group.

    """
    # Calculate number of required groups padding with holding_span-1 for
    # remainder items if holding_span is not a factor of 6_000_000
    num_groups = (6_000_000 + holding_span - 1) // holding_span

    # Build a lazy query filtering on bonds within holding_size and grouping
    # into num_groups to determine the total prizes won in each grouped sim
    q = (
        df.lazy()
        .filter(df["bond"] < holding_size)
        .group_by(pl.col("sim").mod(num_groups).alias("sim_group"))
        .agg(pl.sum("prize").alias("total_won"))
    )
    grouped_df = q.collect()

    # Remove last partial group if total sims is not divisible by holding_span
    if 6_000_000 % holding_span:
        grouped_df = grouped_df.filter(
            pl.col("sim_group").mod(num_groups) != num_groups - 1)
        num_groups -= 1

    # Fill in any gaps created by sims with no prizes
    all_simulations = pl.DataFrame({"sim_group": range(num_groups)},
                                   schema={"sim_group": pl.Int32})

    return all_simulations.join(grouped_df, on="sim_group", how="left",
    ).fill_null(0)


def get_data_holding_sizes(
        df: pl.DataFrame, holding_span: int = 1) -> pl.DataFrame:
    """Call group_df for a specified list of holding sizes and holding_span.

    Also pivots the data into a dataframe of holding size vs total_won
    for each sim_group.

    Returns:
        Pivoted dataframe of holding size vs total_won for each sim_group.

    """
    size_values = [500, 1_000, 2_000, 5_000, 10_000, 20_000, 50_000, 100_000]

    data = [(size, group_df(df, size, holding_span)) for size in size_values]

    pivoted_data: list[pl.Series] = [
        100 * 12 / holding_span / size * group["total_won"].alias(str(size))
        for size, group in data]

    return pl.DataFrame().with_columns(pivoted_data)


def boxplot_holding_sizes(pivoted_df: pl.DataFrame) -> pl.DataFrame:
    """Plot and print statistics for pivoted_df.

    Uses result of get_data_holding_sizes

    Returns:
        Described dataframe

    """
    plt.figure()
    plt.boxplot(pivoted_df, labels=pivoted_df.columns, showfliers=False)
    plt.xlabel("Holding Size (£)")
    plt.ylabel("Median annual return (%)")

    stats = pivoted_df.describe().with_columns(
        [pl.col(col).round(1) for col in pivoted_df.columns])

    with pl.Config(tbl_cols=-1):
        print(stats)  # noqa: T201

    return stats


def get_data_holding_spans(
        df: pl.DataFrame, holding_size: int = 10_000) -> list[pl.Series]:
    """Call group_df for a specified list of holding spans and holding_size.

    Returns:
        Pivoted dataframe of holding span vs total_won for each sim_group.

    """
    span_values = [1, 2, 6, 12, 24, 60, 120, 240, 600]

    data = [(span, group_df(df, holding_size, span))
            for span in span_values]

    return [
        100 * 12 / holding_size / span * group["total_won"].alias(str(span))
        for span, group in data
    ]


def boxplot_holding_spans(pivoted_data: list[pl.Series]) -> pl.DataFrame:
    """Plot and print statistics for pivoted_df from get_data_holding_spans.

    Returns:
        Dataframe of statistics for pivoted_df.

    """
    plt.figure()
    plt.boxplot(pivoted_data,
                labels=[s.name for s in pivoted_data], showfliers=False)
    plt.xlabel("Holding Span (months)")
    plt.ylabel("Median annual return (%)")

    stats = pl.DataFrame(pivoted_data[0].describe()["statistic"]).with_columns(
        [col.describe()["value"].round(2).alias(col.name)
         for col in pivoted_data])

    with pl.Config(tbl_cols=-1):
        print(stats)  # noqa: T201

    return stats


def grouped_matrix(df: pl.DataFrame) -> pl.DataFrame:
    """Call group_df for a specified list of holding sizes and spans.

    Returns:
        Pivoted dataframe of dataframes of holding size vs holding_span.

    """
    size_values = [500, 1_000, 2_000, 5_000, 10_000, 20_000, 50_000, 100_000]
    span_values = [1, 2, 6, 12, 24, 60, 120, 240, 600]

    data = [(size, span, group_df(df, size, span))
            for size in size_values for span in span_values]

    return pl.DataFrame(data, schema=["size", "span", "dataframe"],
                             orient="row")


def median_rate_matrix(matrix_df: pl.DataFrame) -> pl.DataFrame:
    """Calculate median return percentage for matrix_df from grouped_matrix.

    Returns:
        Dataframe of median returns.

    """
    median_prizes = [x.describe().filter(
        pl.col("statistic") == "50%")[0, 2] for x in matrix_df["dataframe"]]

    # Create a new DataFrame using the median prizes
    return matrix_df["size", "span"].with_columns(
        rate=(
            pl.Series(median_prizes) / pl.col("size") / pl.col("span")
            * 12 * 100
        ))


def median_rate_heatmap(rate_df: pl.DataFrame) -> None:
    """Plot and print median returns for rate_df from median_rate_matrix."""
    plt.figure()
    pivoted_rate_df = rate_df.pivot("size", index="span", values="rate")
    print("Median return (%) for various holding sizes and spans")  # noqa: T201
    with pl.Config(tbl_cols=-1):
        print(pivoted_rate_df)  # noqa: T201

    pd_df_piv = pivoted_rate_df.to_pandas().set_index("span").iloc[::-1, :]
    sns.heatmap(pd_df_piv, annot=True, cbar=False)
    plt.xlabel("Holding Size (£)")
    plt.ylabel("Holding Span (months)")
    plt.title("Premium Bond median annual return (%)")

    plt.figure()
    pct_df = rate_df.with_columns(
        (pl.col("rate") / 0.044).round(0).cast(pl.Int16))
    pivoted_rate_df = pct_df.pivot("size", index="span", values="rate")
    print("Median return as a percentage of the prize rate")  # noqa: T201
    with pl.Config(tbl_cols=-1):
        print(pivoted_rate_df)  # noqa: T201

    pd_df_piv = pivoted_rate_df.to_pandas().set_index("span").iloc[::-1, :]
    sns.heatmap(pd_df_piv, annot=True, cbar=False)
    plt.xlabel("Holding Size (£)")
    plt.ylabel("Holding Span (months)")
    plt.title("Premium Bond return (% prize rate)")


if __name__ == "__main__":
    # Load input data
    input_df = pl.read_parquet("premium_bond_6M_sim_202408.parquet")

    # Group by prizes won to see distribution
    df_prizes = input_df.group_by("prize").agg(
        pl.col("prize").len().alias("frequency")).sort("prize").with_columns(
            (pl.col("frequency") * 100 / len(input_df)
            ).alias("percent").round(2),
        )

    with pl.Config(tbl_rows=-1):
        print("Prize distribution")  # noqa: T201
        print(df_prizes)  # noqa: T201

    # Explore prize rate for various holding sizes over 6 months
    pivoted_df = get_data_holding_sizes(input_df, holding_span=6)
    print("Return statistics for various holdings over 6 months")  # noqa: T201
    boxplot_holding_sizes(pivoted_df)
    plt.title("Premium Bond returns over 6 months")

    # Explore prize rate for various holding spans for 10_000 bonds
    pivoted_data = get_data_holding_spans(input_df, holding_size=10_000)
    print("Return statistics for various holding spans for 10,000 bonds")  # noqa: T201
    boxplot_holding_spans(pivoted_data)
    plt.title("Premium Bond returns for a £10,000 holding")

    # Calculate median returns for various holding size and span
    matrix_df = grouped_matrix(input_df)
    rate_df = median_rate_matrix(matrix_df)
    median_rate_heatmap(rate_df)
